/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package register4;

import javax.swing.JOptionPane;
import  register4.userdatabase;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import register4.Message;

/**
 *
 * @author RC_Student_lab
 */
public class Chatbox extends javax.swing.JFrame {
private String loggedInUsername;

    /**
     * Creates new form Chatbox
     */
    public Chatbox(String username) {
        initComponents();
      
        this.loggedInUsername=username;
      
        String firstname=userdatastore.userFirstname.get(loggedInUsername);
        String lastname=userdatastore.userLastname.get(loggedInUsername);
        lblwelcomeUser.setText("Welcome " + firstname + " " + lastname + " it is great to see you. ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnQuickChatMenu = new javax.swing.JButton();
        lblwelcomeUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        btnQuickChatMenu.setBackground(new java.awt.Color(0, 0, 0));
        btnQuickChatMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuickChatMenu.setForeground(new java.awt.Color(204, 204, 204));
        btnQuickChatMenu.setText("Chat:");
        btnQuickChatMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickChatMenuActionPerformed(evt);
            }
        });

        lblwelcomeUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblwelcomeUser.setText("welcome to Quick Chat:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblwelcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuickChatMenu)
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblwelcomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btnQuickChatMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 214, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuickChatMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickChatMenuActionPerformed
       
        Object[] options={"1.Send Message " , "2.Show recently send messages " , "3.Quit"};
        int choice = JOptionPane.showOptionDialog(
                this ,
                "Please select an option from the menu:",
                "QuickChat Main Menu",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
        );
        switch(choice){
            case 0:
                sendMessagesFunction();
                
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Coming Soon." , "Feature Under development",JOptionPane.INFORMATION_MESSAGE);
                break;
            case 2:
                int confirm=JOptionPane.showConfirmDialog(this, "Are you sure you want to quit Quickchat?","confirm Quit",JOptionPane.YES_NO_OPTION);
                if(confirm==JOptionPane.YES_OPTION){
                    this.dispose();
                    System.exit(0);
                }
                    break;
            case JOptionPane.CLOSED_OPTION:
                JOptionPane.showMessageDialog(this,"Menu closed.No action taken.");
           
                }
    }
        private void sendMessagesFunction() {
        //
      
    String numMessagesStr = JOptionPane.showInputDialog(this, "How many messages do you wish to send?");
    if (numMessagesStr == null || numMessagesStr.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Message sending cancelled.");
        return;
    }

    int numberOfMessages;
    try {
        numberOfMessages = Integer.parseInt(numMessagesStr.trim());
        if (numberOfMessages <= 0) {
            JOptionPane.showMessageDialog(this, "Please enter a positive number of messages.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid number entered. Please enter a numeric value.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    for (int i = 0; i < numberOfMessages; i++) {
        JOptionPane.showMessageDialog(this, "Entering Message " + (i + 1) + " of " + numberOfMessages);

        String recipient = JOptionPane.showInputDialog(this, "Enter recipient's cell number (e.g., +27123456789):");
        if (recipient == null || recipient.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Recipient input cancelled or empty. Skipping to next message.", "Warning", JOptionPane.WARNING_MESSAGE);
            continue;
        }
        recipient = recipient.trim();

        if (!Message.checkRecipientCell(recipient)) {
            JOptionPane.showMessageDialog(this, "Recipient cell number incorrect: must be '+27' followed by 9 digits (e.g., +27123456789).", "Input Error", JOptionPane.ERROR_MESSAGE);
            continue;
        }

        String messageContent = JOptionPane.showInputDialog(this, "Enter message content (max 250 characters):");
        if (messageContent == null || messageContent.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Message content input cancelled or empty. Skipping to next message.", "Warning", JOptionPane.WARNING_MESSAGE);
            continue;
        }
        messageContent = messageContent.trim();

        if (!Message.checkMessageContentLength(messageContent)) {
            JOptionPane.showMessageDialog(this, "Please enter a message of less than 250 characters.", "Input Error", JOptionPane.ERROR_MESSAGE);
            continue;
        }

        // Create the message
        Message currentMessage = new Message(loggedInUsername, recipient, messageContent);

        // Ask user what to do with the message
        Object[] messageOptions = {"Send Message", "Disregard Message", "Store Message"};
        int userChoice = JOptionPane.showOptionDialog(
                this,
                "Choose what you want to do with this message:\n" + currentMessage.toString(),
                "Message Action",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                messageOptions,
                messageOptions[0]
        );

        switch (userChoice) {
            case 0: // Send
                Message.sendMessage(currentMessage);
                JOptionPane.showMessageDialog(this, currentMessage.toString(), "Message Sent", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 1: // Disregard
                JOptionPane.showMessageDialog(this, "Message disregarded.", "Info", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 2: // Store
                Message.storeMessage(currentMessage);
                JOptionPane.showMessageDialog(this, "Message stored for later.", "Info", JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(this, "No action taken on the message.", "Info", JOptionPane.INFORMATION_MESSAGE);
                break;
        }
    }
    // Show total messages sent
    JOptionPane.showMessageDialog(this, "Total messages: " + Message.returnTotalMessages(), "Total Messages Sent", JOptionPane.INFORMATION_MESSAGE);



        // "The total number of messages should be accumulated and displayed once all the messages have been sent."


    }//GEN-LAST:event_btnQuickChatMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chatbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chatbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chatbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chatbox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chatbox("Quickchat").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuickChatMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblwelcomeUser;
    // End of variables declaration//GEN-END:variables
}
